Repository moira-alert/moira, pull requests merged in 2019-10, with the labels that each got.

#409 Feature/getmaintenanceinfomessage to notifier
  checker/check_test.go
  checker/event.go
  checker/event_test.go
  checker/maintenance.go
  checker/maintenance_test.go
  datatypes.go
  datatypes_test.go
  mock/moira-alert/logger.go
  senders/discord/send.go
  senders/discord/send_test.go
  senders/mail/send.go
  senders/opsgenie/send.go
  senders/opsgenie/send_test.go
  senders/pagerduty/send.go
  senders/pagerduty/send_test.go
  senders/pushover/pushover.go
  senders/pushover/pushover_test.go
  senders/script/script_test.go
  senders/slack/slack.go
  senders/slack/slack_test.go
  senders/telegram/send.go
  senders/telegram/send_test.go
  senders/twilio/sms.go
  senders/twilio/sms_test.go
  senders/victorops/send.go
  senders/victorops/send_test.go
Labels: backend, enhancement

#440 build: Change naming for feature docker images
  Makefile
Labels: delivery, enhancement

#443 Add subscription transfer and contact deletion to CLI
  cmd/cli/main.go
  cmd/cli/user.go
Labels: backend, feature

#432 Msteams support
  local/api.yml
  notifier/registrator.go
  senders/msteams/datatypes.go
  senders/msteams/msteams.go
  senders/msteams/msteams_test.go
Labels: backend, feature

#439 Upgrade golangci-lint to v1.21.0
  .golangci.yml
  .travis.yml
  Makefile
Labels: backend, delivery
