Repository moira-alert/moira, pull requests merged in 2020-02, with the labels that each got.

#485 docs: Add community guides
  .github/CODEOWNERS
  .github/CODE_OF_CONDUCT.md
  .github/CONTRIBUTING.md
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/PULL_REQUEST_TEMPLATE.md
  README.md
Labels: doc, enhancement

#495 fix(notifier): Move plot boundaries
  filter/cache_storage.go
  helpers.go
  helpers_test.go
  notifier/plotting.go
  notifier/plotting_test.go
Labels: backend, bug

#496 pefr(filter): Reduce nodes slice capacity
  filter/pattern_index.go
Labels: backend, enhancement
