Repository moira-alert/moira, pull requests merged in 2020-03, with the labels that each got.

#498 feat(api): Implement stable pagination
  api/controller/triggers.go
  api/controller/triggers_test.go
  api/dto/triggers.go
  api/handler/triggers.go
  api/middleware/context.go
  api/middleware/middleware.go
  database/redis/reply/search_result.go
  database/redis/triggers_search_results.go
  database/redis/triggers_search_results_test.go
  interfaces.go
  mock/moira-alert/database.go
Labels: backend, feature

#497 Enable pprof heap handler
  cmd/telemetry.go
Labels: backend, enhancement

#504 build: Upgrade to Go 1.14
  .travis.yml
  Dockerfile.api
  Dockerfile.checker
  Dockerfile.cli
  Dockerfile.filter
  Dockerfile.notifier
  go.mod
  metric_source/remote/remote_test.go
Labels: backend, enhancement

#468 Add reviewdog
  .reviewdog.yml
  .travis.yml
  Makefile
Labels: backend, delivery

#515 Improve docker-compose
  docker-compose.yml
Labels: CI/CD, tooling

#517 Fix pattern matching in filter
  filter/pattern_index.go
  filter/pattern_index_test.go
Labels: backend, bug
